#define CONFIG_ARRAY  1




#define CONFIG_LEETCODE_01
#define CONFIG_LEETCODE_02
#define CONFIG_LEETCODE_03
#define CONFIG_LEETCODE_04
#define CONFIG_LEETCODE_05
#define CONFIG_LEETCODE_06
#define CONFIG_LEETCODE_07
